/*
Vigo Bus Core API

This is the API for the Vigo Bus Core project.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSchedule{}

// ApiSchedule struct for ApiSchedule
type ApiSchedule struct {
	// Line is the line that the schedule is for
	Line *ApiLine `json:"line,omitempty"`
	// Route is the route that the schedule is for
	Route *string `json:"route,omitempty"`
	// Time is the time of the schedule
	Time *int32 `json:"time,omitempty"`
}

// NewApiSchedule instantiates a new ApiSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSchedule() *ApiSchedule {
	this := ApiSchedule{}
	return &this
}

// NewApiScheduleWithDefaults instantiates a new ApiSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiScheduleWithDefaults() *ApiSchedule {
	this := ApiSchedule{}
	return &this
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *ApiSchedule) GetLine() ApiLine {
	if o == nil || IsNil(o.Line) {
		var ret ApiLine
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSchedule) GetLineOk() (*ApiLine, bool) {
	if o == nil || IsNil(o.Line) {
		return nil, false
	}
	return o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *ApiSchedule) HasLine() bool {
	if o != nil && !IsNil(o.Line) {
		return true
	}

	return false
}

// SetLine gets a reference to the given ApiLine and assigns it to the Line field.
func (o *ApiSchedule) SetLine(v ApiLine) {
	o.Line = &v
}

// GetRoute returns the Route field value if set, zero value otherwise.
func (o *ApiSchedule) GetRoute() string {
	if o == nil || IsNil(o.Route) {
		var ret string
		return ret
	}
	return *o.Route
}

// GetRouteOk returns a tuple with the Route field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSchedule) GetRouteOk() (*string, bool) {
	if o == nil || IsNil(o.Route) {
		return nil, false
	}
	return o.Route, true
}

// HasRoute returns a boolean if a field has been set.
func (o *ApiSchedule) HasRoute() bool {
	if o != nil && !IsNil(o.Route) {
		return true
	}

	return false
}

// SetRoute gets a reference to the given string and assigns it to the Route field.
func (o *ApiSchedule) SetRoute(v string) {
	o.Route = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ApiSchedule) GetTime() int32 {
	if o == nil || IsNil(o.Time) {
		var ret int32
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSchedule) GetTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ApiSchedule) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given int32 and assigns it to the Time field.
func (o *ApiSchedule) SetTime(v int32) {
	o.Time = &v
}

func (o ApiSchedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Line) {
		toSerialize["line"] = o.Line
	}
	if !IsNil(o.Route) {
		toSerialize["route"] = o.Route
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableApiSchedule struct {
	value *ApiSchedule
	isSet bool
}

func (v NullableApiSchedule) Get() *ApiSchedule {
	return v.value
}

func (v *NullableApiSchedule) Set(val *ApiSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSchedule(val *ApiSchedule) *NullableApiSchedule {
	return &NullableApiSchedule{value: val, isSet: true}
}

func (v NullableApiSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


